model_path: "/home/eeyifanshen/e2e_audio_LLM/dialog_turntaking_new/Freeze-Omni/checkpoints"
llm_path: "/home/eeyifanshen/e2e_audio_LLM/dialog_turntaking_new/Freeze-Omni/Qwen2-7B-Instruct"
device: 'cuda:0' 
thread_sleep_interval: 0.005
debug_time: False

audio:
  expected_sampling_rate: 16000 # From dialog_state_monitoring.html, line 306


vad:
  use_standalone_vad: true # From start_monitoring.sh, line 48 (flag is present)
  vad_threshold: 0.8 # From PureVAD.py, line 16
  min_silent_duration_second: 0.3 # From PureVAD.py, line 17 (300ms)
  speech_pad_second: 0.03 # From PureVAD.py, line 18 (30ms)
  vad_history_cache_chunk_cnt: 10 # From PureVAD.py, line 10


audio_feature_gating:
  feature_gating_history_size: 10 # From AudioFeatureGating.py, line 14
  onset_input_chunk_cache_size: 0 # From AudioFeatureGating.py, line 15

  fbank:
    expected_audio_chunk_duration_in_sec: 0.224 ## 225ms
    feat_dim: 80 # From AudioFeatureGating.py, line 10
    audio_to_proc_per_step_in_sec: 0.016 ##16ms
    step_size_in_sec: 0.008 ## 10ms
    context_duration_in_sec: 0.032 ## 32ms overlap for each input chunk


inference_control:
  top_k: 5 # From server_alt.py, line 35 (argparse default)
  top_p: 0.8 # From server_alt.py, line 36 (argparse default)
  temperature: 0.7 # From server_alt.py, line 37 (argparse default)
  # default_prompt: "You are a helpful voice assistant. Your answer should be coherent, natural, simple, complete. Your name is Xiao Yun. Your inventor is Tencent." # From server_alt.py, line 90
  default_prompt: "" # From server_alt.py, line 90


dialog_state_decision:
  resp_threshold: 0.5